- name: Create Directory for Client Configuration Files
  ansible.builtin.file:
    path: "{{ client_configuration_directory }}"
    state: directory
    mode: "0644"

- name: Create Client Key
  community.crypto.openssl_privatekey:
    path: "{{ pki_directory }}/client.key"
    type: ECC
    curve: secp384r1

- name: Create Client CSR
  community.crypto.openssl_csr:
    path: "{{ pki_directory }}/client.csr"
    privatekey_path: "{{ pki_directory }}/client.key"
    mode: "0400"
    common_name: OpenVPN Client
    key_usage:
      - digitalSignature
    extended_key_usage:
      - clientAuth
    basic_constraints:
      - CA:FALSE

- name: Sign Client Certificate
  community.crypto.x509_certificate:
    path: "{{ pki_directory }}/client.crt"
    csr_path: "{{ pki_directory }}/client.csr"
    ownca_path: "{{ pki_directory }}/ca.crt"
    ownca_privatekey_path: "{{ pki_directory }}/ca.key"
    provider: ownca

- name: Copy Key and Certificate to Configuration Directory
  ansible.builtin.copy:
    src: "{{ pki_directory }}/{{ item }}"
    dest: "{{ client_configuration_directory }}/{{ item }}"
    remote_src: true
    mode: preserve
  loop:
    - client.key
    - client.crt

- name: Read Files to Create Client ovpn File
  ansible.builtin.slurp:
    src: "{{ item }}"
  register: slurpfile
  loop:
    - "{{ openvpn_server_directory }}/ca.crt"
    - "{{ client_configuration_directory }}/client.key"
    - "{{ client_configuration_directory }}/client.crt"
    - "{{ openvpn_server_directory }}/ta.key"

- name: Print slurpfile
  ansible.builtin.debug:
    msg: "{{ slurpfile }}"

- name: Set Server IP to Vagrant IP
  when: target_type == "vagrant"
  ansible.builtin.set_fact:
    vpn_server_ip: "{{ ansible_default_ipv4.address }}"

- name: Set Variables for Client Configuration Template
  ansible.builtin.set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop:
    - key: ca_information
      value: "{{ slurpfile.results[0].content | b64decode }}"
    - key: private_key_information
      value: "{{ slurpfile.results[1].content | b64decode }}"
    - key: certificate_information
      value: "{{ slurpfile.results[2].content | b64decode }}"
    - key: static_key_information
      value: "{{ slurpfile.results[3].content | b64decode }}"

- name: Create Client File
  ansible.builtin.template:
    src: client.conf.j2
    dest: "{{ client_configuration_directory }}/client.ovpn"
    mode: "0644"

- name: Copy Client Configuration File to Controller
  ansible.builtin.fetch:
    src: "{{ client_configuration_directory }}/client.ovpn"
    dest: "{{ client_configuration_file_target }}/client.ovpn"
    flat: true
